services:
  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # FastAPI
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - uploads_volume:/app/data
      - outputs_volume:/app/outputs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  # Celery Worker Service
  worker:
    build: .
    command: celery -A celery_tasks.celery worker --loglevel=info -P eventlet
    volumes:
      - .:/app
      - uploads_volume:/app/data
      - outputs_volume:/app/outputs
    env_file:
      - .env
    depends_on:
      - redis

volumes:
  uploads_volume:
  outputs_volume: